import { cookies } from "next/headers";
import { OEEProvider } from "@/components/oee/OEEContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let initialUser = null;
  try {
    const cookieStore = await cookies();
    const raw = cookieStore.get("oee_user")?.value;
    if (raw) initialUser = JSON.parse(decodeURIComponent(raw));
  } catch {
    initialUser = null;
  }

  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <OEEProvider initialUser={initialUser}>{children}</OEEProvider>
      </body>
    </html>
  );
}
