import { cookies } from "next/headers";
import Script from "next/script";
import { OEEProvider } from "@/components/oee/OEEContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let initialUser = null;
  try {
    const cookieStore = await cookies();
    const raw = cookieStore.get("oee_user")?.value;
    if (raw) initialUser = JSON.parse(decodeURIComponent(raw));
  } catch {
    initialUser = null;
  }

  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Script
          id="oee-theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var t=localStorage.getItem('oee:theme')||'auto';var el=document.documentElement;if(t==='dark'||t==='light'){el.setAttribute('data-theme',t);}else{el.removeAttribute('data-theme');}}catch(e){}})();",
          }}
        />
        <OEEProvider initialUser={initialUser}>{children}</OEEProvider>
      </body>
    </html>
  );
}
